resources:
  - name: x86_64_CentOS_7_prep_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/x86_64.CentOS_7.prep
      branch: master

  - name: CentOS7_bits_ecr_cli
    type: cliConfig
    integration: ecr_bits_push
    pointer:
      region: us-east-1

  - name: CentOS7_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

  - name: CentOS7_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: CentOS7_reqExec_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqExec
      branch: master

jobs:
  # TODO: move this job to x86_64 CentOS_7
  - name: reqExec_x86_64_CentOS_7_pack
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_CentOS_7_prep_repo
        switch: off
      - IN: CentOS7_bits_access_cli
        switch: off
      - IN: microbase_img
      - IN: CentOS7_reqExec_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_CentOS_7_prep_repo")
            - ./buildAndPushReqExecArtifacts.sh CentOS7_reqExec_repo
            - popd
